version: "1"
rules:
  - base: main
    upstream: enthec/webappanalyzer:main    # the owner of upstream repo
    mergeMethod: rebase
    mergeUnstable: false
    assignees: # Optional
      - berishaerblin
      - mlec1
      - red667
    reviewers: # Optional
      - berishaerblin
      - mlec1
      - red667
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - berishaerblin
      - mlec1
      - red667